### ISSUE TITLE
Make test fail when doctest fails

### ISSUE THREAD

**Issue by cemsbr** [kytos/python-openflow#169]
Currently, doctest runs before unit tests. If a doctest fails, the output can be seen only by scrolling the screen and the test passes in CI. The tests should fail if a doctest fails.

Possible solution (need to search the right way to do it): in setup.py, Doctest class, check whether it fails and, if it does, exit with a proper error code.

**Comment by diraol** [comment]
@cemsbr this issue has been resolved?

**Comment by cemsbr** [comment]
No, @diraol. #170 references this issue, but didn't solve this problem.
